switch from 6.0 to 6.0.3
It conforms with default mongo_k8s_tag: 6.0.3-debian-11-r20
and 6.0.3 can be downloaded via download-frozen-image-v2.sh.

./download-frozen-image-v2.sh xtestingci/ mongo:6.0.12
error: unknown manifest mediaType (library/mongo:6.0.12@6.0.12): 'application/vnd.oci.image.index.v1+json'

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>